start =
    atom

nl = "\n"

validchar
    = [0-9a-zA-Z_?!+-=@#$%^&*/.]

comment = ";;" (!nl .)*

ws = (comment / nl / [ \t]+)*

spaceatom = ws first:atom
       {return first}

atom = ws "'" first:atom
     {return ["quote",first];}
    / ws chars:validchar+ ws 
        { return chars.join(""); }
    / ws "(" first:atom second:spaceatom* ")" ws
        {return [first].concat(second);}